### ISSUE TITLE
support 4o

### ISSUE THREAD

**Issue by XDavidT** [darylhcw/self-hosted-gpt#1]
Can you add support for gpt 4o?

**Comment by darylhcw** [comment]
Hey, I've added GPT-4o as an option!

**Comment by david-nano** [comment]
Not sure it been used well: https://i.imgur.com/mjzyC4I.png

**Comment by darylhcw** [comment]
Using a prompt is not a good way to check the specific model. I think GPT itself does not know if it is standard GPT-4/GPT-4o/etc:
Here's me using the same prompt on the OpenAI website with GPT-4o:
![image](https://github.com/darylhcw/self-hosted-gpt/assets/27339687/8acd1fa9-6bd6-4768-a5c5-6da708756f74)


___

You can check the network tab in dev tools to see that we are correctly sending "gpt-4o" in the request to OpenAI:

![image](https://github.com/darylhcw/self-hosted-gpt/assets/27339687/36cb5403-4fe4-44f1-8a2b-6f3643840ff6)

**Comment by david-nano** [comment]
Got same result as you today.
But few days back it reply to me 4o some how.. never mind, thx.
